In [1]:
import pandas as pd
import numpy as nu
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

In [25]:
df = pd.read_csv("../data/raw/luad_tcga_gdc_clinical_data.tsv", sep="\t")
df.head()

,Study ID,Patient ID,Sample ID,Diagnosis Age,American Joint Committee on Cancer Publication Version Type,Biopsy Site,Cancer Type,Cancer Type Detailed,Last Communication Contact from Initial Pathologic Diagnosis Date,Birth from Initial Pathologic Diagnosis Date,Death from Initial Pathologic Diagnosis Date,Disease Free (Months),Disease Free Status,Disease Type,Ethnicity Category,Fraction Genome Altered,ICD-10 Classification,Is FFPE,Morphology,Mutation Count,Oncotree Code,Overall Survival (Months),Overall Survival Status,Other Patient ID,Other Sample ID,AJCC Pathologic M-Stage,AJCC Pathologic N-Stage,AJCC Pathologic Stage,AJCC Pathologic T-Stage,Primary Diagnosis,Patient Primary Tumor Site,Prior Malignancy,Prior Treatment,Project Identifier,Project Name,Project State,Race Category,Number of Samples Per Patient,Sample Type,Sample type id,Sex,Years Smoked,Person Cigarette Smoking History Pack Year Value,TMB (nonsynonymous),Patient's Vital Status,Year of Diagnosis
0,luad_tcga_gdc,TCGA-05-4244,TCGA-05-4244-01,70.0,6th,Lung,Lung Adenocarcinoma,Lung Adenocarcinoma,0.0,-25752.0,NaN,NaN,NaN,Lung Adenocarcinoma- Not Otherwise Specified (...,NaN,0.4448,C34.3,NO,8140/3,183.0,LUAD,0.000000,0:LIVING,34040b83-7e8a-4264-a551-b16621843e28,bac0b02d-ac3b-4784-b8bf-180eadd548a3,M1,N2,Stage IV,T2,Lung Adenocarcinoma- Not Otherwise Specified (...,Lung,False,False,TCGA-LUAD,Lung Adenocarcinoma,released,NaN,1,Primary Tumor,1,Male,NaN,38.0,6.100000,Alive,2009.0
1,luad_tcga_gdc,TCGA-05-4249,TCGA-05-4249-01,67.0,6th,Lung,Lung Adenocarcinoma,Lung Adenocarcinoma,1158.0,-24532.0,NaN,NaN,NaN,Lung Adenocarcinoma- Not Otherwise Specified (...,NaN,0.2488,C34.3,NO,8140/3,274.0,LUAD,50.032852,0:LIVING,4addf05f-3668-4b3f-a17f-c0227329ca52,80f196fe-1eaf-40cb-ab58-c84795acc5c7,M0,N0,Stage IB,T2,Lung Adenocarcinoma- Not Otherwise Specified (...,Lung,False,False,TCGA-LUAD,Lung Adenocarcinoma,released,NaN,1,Primary Tumor,1,Male,NaN,52.0,9.133333,Alive,2007.0
2,luad_tcga_gdc,TCGA-05-4250,TCGA-05-4250-01,79.0,6th,Lung,Lung Adenocarcinoma,Lung Adenocarcinoma,NaN,-29068.0,121.0,10.980702,1:Recurred/Progressed,Lung Adenocarcinoma- Not Otherwise Specified (...,NaN,0.3679,C34.3,NO,8140/3,297.0,LUAD,3.975033,1:DECEASED,f98ecd8a-b878-4f53-b911-20cd8e17281c,8f274178-7a8e-46b6-8d2c-900338bbb946,M0,N1,Stage IIIA,T3,Lung Adenocarcinoma- Not Otherwise Specified (...,Lung,False,False,TCGA-LUAD,Lung Adenocarcinoma,released,NaN,1,Primary Tumor,1,Female,NaN,47.0,9.900000,Dead,2007.0
3,luad_tcga_gdc,TCGA-05-4382,TCGA-05-4382-01,68.0,6th,Lung,Lung Adenocarcinoma,Lung Adenocarcinoma,607.0,-24868.0,NaN,NaN,NaN,Lung Adenocarcinoma Mixed Subtype,NaN,0.1301,C34.1,NO,8255/3,1405.0,LUAD,19.940867,0:LIVING,3434b91a-c05f-460f-a078-7b1bb6e7085d,cce6d71f-369e-467f-bd7e-03d20e97b7f3,M0,N0,Stage IB,T2,Lung Adenocarcinoma Mixed Subtype,Lung,True,False,TCGA-LUAD,Lung Adenocarcinoma,released,NaN,1,Primary Tumor,1,Male,NaN,62.0,46.800000,Alive,2009.0
4,luad_tcga_gdc,TCGA-05-4384,TCGA-05-4384-01,66.0,6th,Lung,Lung Adenocarcinoma,Lung Adenocarcinoma,426.0,-24411.0,NaN,NaN,NaN,Lung Adenocarcinoma Mixed Subtype,NaN,0.0758,C34.3,NO,8255/3,102.0,LUAD,13.994744,0:LIVING,9a50e7e4-831d-489f-87d2-979e987561cc,e4416303-50b0-4316-bfee-030c7b29fac6,M0,N2,Stage IIIA,T2,Lung Adenocarcinoma Mixed Subtype,Lung,True,False,TCGA-LUAD,Lung Adenocarcinoma,released,NaN,1,Primary Tumor,1,Male,24.0,20.0,3.400000,Alive,2009.0

In [26]:
df.shape

(571, 46)

In [31]:
df.columns.tolist()

['Study ID',
 'Patient ID',
 'Sample ID',
 'Diagnosis Age',
 'American Joint Committee on Cancer Publication Version Type',
 'Biopsy Site',
 'Cancer Type',
 'Cancer Type Detailed',
 'Last Communication Contact from Initial Pathologic Diagnosis Date',
 'Birth from Initial Pathologic Diagnosis Date',
 'Death from Initial Pathologic Diagnosis Date',
 'Disease Free (Months)',
 'Disease Free Status',
 'Disease Type',
 'Ethnicity Category',
 'Fraction Genome Altered',
 'ICD-10 Classification',
 'Is FFPE',
 'Morphology',
 'Mutation Count',
 'Oncotree Code',
 'Overall Survival (Months)',
 'Overall Survival Status',
 'Other Patient ID',
 'Other Sample ID',
 'AJCC Pathologic M-Stage',
 'AJCC Pathologic N-Stage',
 'AJCC Pathologic Stage',
 'AJCC Pathologic T-Stage',
 'Primary Diagnosis',
 'Patient Primary Tumor Site',
 'Prior Malignancy',
 'Prior Treatment',
 'Project Identifier',
 'Project Name',
 'Project State',
 'Race Category',
 'Number of Samples Per Patient',
 'Sample Type',
 'Sample type id',
 'Sex',
 'Years Smoked',
 'Person Cigarette Smoking History Pack Year Value',
 'TMB (nonsynonymous)',
 "Patient's Vital Status",
 'Year of Diagnosis']

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 571 entries, 0 to 570
Data columns (total 46 columns):
 #   Column                                                             Non-Null Count  Dtype
---  ------                                                             --------------  -----
 0   Study ID                                                           571 non-null    object
 1   Patient ID                                                         571 non-null    object
 2   Sample ID                                                          571 non-null    object
 3   Diagnosis Age                                                      490 non-null    float64
 4   American Joint Committee on Cancer Publication Version Type        498 non-null    object
 5   Biopsy Site                                                        521 non-null    object
 6   Cancer Type                                                        571 non-null    object
 7   Cancer Type Detailed                                               571 non-null    object
 8   Last Communication Contact from Initial Pathologic Diagnosis Date  386 non-null    float64
 9   Birth from Initial Pathologic Diagnosis Date                       490 non-null    float64
 10  Death from Initial Pathologic Diagnosis Date                       184 non-null    float64
 11  Disease Free (Months)                                              291 non-null    float64
 12  Disease Free Status                                                294 non-null    object
 13  Disease Type                                                       521 non-null    object
 14  Ethnicity Category                                                 395 non-null    object
 15  Fraction Genome Altered                                            520 non-null    float64
 16  ICD-10 Classification                                              521 non-null    object
 17  Is FFPE                                                            571 non-null    object
 18  Morphology                                                         521 non-null    object
 19  Mutation Count                                                     559 non-null    float64
 20  Oncotree Code                                                      571 non-null    object
 21  Overall Survival (Months)                                          512 non-null    float64
 22  Overall Survival Status                                            521 non-null    object
 23  Other Patient ID                                                   521 non-null    object
 24  Other Sample ID                                                    571 non-null    object
 25  AJCC Pathologic M-Stage                                            517 non-null    object
 26  AJCC Pathologic N-Stage                                            520 non-null    object
 27  AJCC Pathologic Stage                                              513 non-null    object
 28  AJCC Pathologic T-Stage                                            521 non-null    object
 29  Primary Diagnosis                                                  521 non-null    object
 30  Patient Primary Tumor Site                                         521 non-null    object
 31  Prior Malignancy                                                   480 non-null    object
 32  Prior Treatment                                                    520 non-null    object
 33  Project Identifier                                                 571 non-null    object
 34  Project Name                                                       571 non-null    object
 35  Project State                                                      571 non-null    object
 36  Race Category                                                      455 non-null    object
 37  Number of Samples Per Patient                                      571 non-null    int64
 38  Sample Type                                                        571 non-null    object
 39  Sample type id                                                     571 non-null    int64
 40  Sex                                                                521 non-null    object
 41  Years Smoked                                                       194 non-null    float64
 42  Person Cigarette Smoking History Pack Year Value                   354 non-null    float64
 43  TMB (nonsynonymous)                                                559 non-null    float64
 44  Patient's Vital Status                                             521 non-null    object
 45  Year of Diagnosis                                                  511 non-null    float64
dtypes: float64(12), int64(2), object(32)
memory usage: 205.3+ KB

In [29]:
df.describe(include="all")

,Study ID,Patient ID,Sample ID,Diagnosis Age,American Joint Committee on Cancer Publication Version Type,Biopsy Site,Cancer Type,Cancer Type Detailed,Last Communication Contact from Initial Pathologic Diagnosis Date,Birth from Initial Pathologic Diagnosis Date,Death from Initial Pathologic Diagnosis Date,Disease Free (Months),Disease Free Status,Disease Type,Ethnicity Category,Fraction Genome Altered,ICD-10 Classification,Is FFPE,Morphology,Mutation Count,Oncotree Code,Overall Survival (Months),Overall Survival Status,Other Patient ID,Other Sample ID,AJCC Pathologic M-Stage,AJCC Pathologic N-Stage,AJCC Pathologic Stage,AJCC Pathologic T-Stage,Primary Diagnosis,Patient Primary Tumor Site,Prior Malignancy,Prior Treatment,Project Identifier,Project Name,Project State,Race Category,Number of Samples Per Patient,Sample Type,Sample type id,Sex,Years Smoked,Person Cigarette Smoking History Pack Year Value,TMB (nonsynonymous),Patient's Vital Status,Year of Diagnosis
count,571,571,571,490.000000,498,521,571,571,386.000000,490.000000,184.000000,291.000000,294,521,395,520.000000,521,571,521,559.000000,571,512.000000,521,521,571,517,520,513,521,521,521,480,520,571,571,571,455,571.000000,571,571.000000,521,194.000000,354.000000,559.000000,521,511.000000
unique,1,569,571,NaN,5,1,1,1,NaN,NaN,NaN,NaN,2,12,2,NaN,7,1,12,NaN,1,NaN,2,519,571,5,5,9,9,12,1,2,2,1,1,1,4,NaN,2,NaN,2,NaN,NaN,NaN,2,NaN
top,luad_tcga_gdc,TCGA-50-5066,TCGA-S2-AA1A-01,NaN,7th,Lung,Lung Adenocarcinoma,Lung Adenocarcinoma,NaN,NaN,NaN,NaN,0:DiseaseFree,Lung Adenocarcinoma- Not Otherwise Specified (...,NOT HISPANIC OR LATINO,NaN,C34.1,NO,8140/3,NaN,LUAD,NaN,0:LIVING,3199cfe5-3be3-43cd-a36b-5cf2c7a9929f,a28cc4b4-4819-41ef-adf7-34ee50e29ba6,M0,N0,Stage IB,T2,Lung Adenocarcinoma- Not Otherwise Specified (...,Lung,False,False,TCGA-LUAD,Lung Adenocarcinoma,released,WHITE,NaN,Primary Tumor,NaN,Female,NaN,NaN,NaN,Alive,NaN
freq,571,2,1,NaN,270,521,571,571,NaN,NaN,NaN,NaN,206,324,388,NaN,315,571,314,NaN,571,NaN,333,2,1,351,336,141,170,324,521,429,517,571,571,571,393,NaN,569,NaN,278,NaN,NaN,NaN,333,NaN
mean,NaN,NaN,NaN,65.222449,NaN,NaN,NaN,NaN,451.183938,-24011.365306,790.413043,30.282493,NaN,NaN,NaN,0.275997,NaN,NaN,NaN,242.000000,NaN,29.771874,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.007005,NaN,1.003503,NaN,31.634021,41.838277,8.562552,NaN,2008.379648
std,NaN,NaN,NaN,10.015607,NaN,NaN,NaN,NaN,824.350827,3656.567935,700.856387,31.105335,NaN,NaN,NaN,0.187730,NaN,NaN,NaN,256.870991,NaN,29.334768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.083477,NaN,0.059131,NaN,12.753749,27.165932,10.239166,NaN,4.175641
min,NaN,NaN,NaN,33.000000,NaN,NaN,NaN,NaN,0.000000,-32432.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,1.000000,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,1.000000,NaN,2.000000,0.150000,0.033333,NaN,1991.000000
25%,NaN,NaN,NaN,59.000000,NaN,NaN,NaN,NaN,35.000000,-26622.750000,297.750000,13.577933,NaN,NaN,NaN,0.119025,NaN,NaN,NaN,67.500000,NaN,13.690867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,1.000000,NaN,20.000000,20.250000,2.400000,NaN,2007.000000
50%,NaN,NaN,NaN,66.000000,NaN,NaN,NaN,NaN,162.000000,-24406.500000,615.500000,19.988822,NaN,NaN,NaN,0.254000,NaN,NaN,NaN,162.000000,NaN,21.567017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,1.000000,NaN,32.000000,40.000000,5.533333,NaN,2010.000000
75%,NaN,NaN,NaN,72.000000,NaN,NaN,NaN,NaN,504.750000,-21735.000000,1120.000000,37.380412,NaN,NaN,NaN,0.410700,NaN,NaN,NaN,322.000000,NaN,37.294678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,1.000000,NaN,40.000000,50.000000,10.883333,NaN,2011.000000
max,NaN,NaN,NaN,88.000000,NaN,NaN,NaN,NaN,6812.000000,-12179.000000,4961.000000,238.287800,NaN,NaN,NaN,0.791300,NaN,NaN,NaN,1880.000000,NaN,238.107753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,2.000000,NaN,64.000000,154.000000,112.366667,NaN,2013.000000

In [30]:
df.isnull().sum().sort_values(ascending=False)

Death from Initial Pathologic Diagnosis Date                         387
Years Smoked                                                         377
Disease Free (Months)                                                280
Disease Free Status                                                  277
Person Cigarette Smoking History Pack Year Value                     217
Last Communication Contact from Initial Pathologic Diagnosis Date    185
Ethnicity Category                                                   176
Race Category                                                        116
Prior Malignancy                                                      91
Diagnosis Age                                                         81
Birth from Initial Pathologic Diagnosis Date                          81
American Joint Committee on Cancer Publication Version Type           73
Year of Diagnosis                                                     60
Overall Survival (Months)                                             59
AJCC Pathologic Stage                                                 58
AJCC Pathologic M-Stage                                               54
Prior Treatment                                                       51
Fraction Genome Altered                                               51
AJCC Pathologic N-Stage                                               51
Overall Survival Status                                               50
Disease Type                                                          50
Biopsy Site                                                           50
Patient's Vital Status                                                50
Primary Diagnosis                                                     50
Sex                                                                   50
Patient Primary Tumor Site                                            50
AJCC Pathologic T-Stage                                               50
Other Patient ID                                                      50
Morphology                                                            50
ICD-10 Classification                                                 50
Mutation Count                                                        12
TMB (nonsynonymous)                                                   12
Cancer Type Detailed                                                   0
Sample ID                                                              0
Study ID                                                               0
Cancer Type                                                            0
Patient ID                                                             0
Is FFPE                                                                0
Other Sample ID                                                        0
Oncotree Code                                                          0
Project Name                                                           0
Project Identifier                                                     0
Number of Samples Per Patient                                          0
Project State                                                          0
Sample Type                                                            0
Sample type id                                                         0
dtype: int64